### ISSUE TITLE
Menu cosmetics

### ISSUE THREAD

**Issue by mcfreem** [nsmader/sim-based-power-calculator#7]
- Clean up top row. Make all same length (delete some spacing between title and radio buttons
- Change method of estimating treatment effect so reads: "Prevalence" or "Odds Ratio"
- Move "prevalence under control conditions above method of estimating treatment effect
- Number of values to test in this range is a bit counter-intuitive. We may need to define.
- Get rid of ICC equation for now.

**Comment by nsmader** [comment]
Have all of this solved except for making the top row "well panels" the same length. Looking at shiny's documentation, it's not immediately clear to me how to solve that. For now, I've opted to remove them so that they have no background and thus no apparent unevenness.
